### ISSUE TITLE
License GPLv3 vs MIT - derivative work

### ISSUE THREAD

**Issue by gohf** [Papakura/urn#1]
The Papakura/urn project states that:

> This code is largely a port of the Java library urnlib

However, it its licensed as MIT while urnlib is licensed under the [GPLv3](https://github.com/slub/urnlib/blob/master/LICENSE).

Is this project not classed as derivative work under the terms of the GPLv3? Should this project actually be licensed under GPLv3. Is MIT License compatable when it does not use the copy left rule?

**Comment by Papakura** [comment]
Updated
